version: '3.8'

services:
  # Nessie Server
  nessie:
    image: projectnessie/nessie:latest
    container_name: nessie
    ports:
      - "19120:19120"
    environment:
      - QUARKUS_HTTP_PORT=19120
    networks:
      - nessie-trino-network

  # Trino Coordinator
  trino-coordinator:
    image: trinodb/trino:latest
    container_name: trino-coordinator
    ports:
      - "8080:8080"
    environment:
      - NESSIE_URI=http://nessie:19120/api/v1
    volumes:
      - ./trino-config:/etc/trino
    depends_on:
      - nessie
    networks:
      - nessie-trino-network

  # Trino Worker (optional, for distributed setup)
  trino-worker:
    image: trinodb/trino:latest
    container_name: trino-worker
    environment:
      - NESSIE_URI=http://nessie:19120/api/v1
    volumes:
      - ./trino-config:/etc/trino
    depends_on:
      - trino-coordinator
    networks:
      - nessie-trino-network

  # MinIO (S3-compatible storage for sample data)
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - nessie-trino-network

networks:
  nessie-trino-network:
    driver: bridge